### ISSUE TITLE
HTML imports deprecated

### ISSUE THREAD

**Issue by raphaelmue** [raphaelmue/dashup#22]
In Google Chrome, HTML imports will be removed soon. There has to be another way to import HTML files due to using Web Components. Else we must consider changing our framework from Web Components to XML.

**Comment by fidsusj** [comment]
Don't worry, we will have to move to ES6 Module imports, which is not going to be a big thing.

**Comment by joshuaschu** [comment]
@fidsusj Will ES6 Module imports work in firefox and edge?

**Comment by raphaelmue** [comment]
Continued in #36
