### ISSUE TITLE
name of updateSettings(User user) is very confusing

### ISSUE THREAD

**Issue by joshuaschu** [raphaelmue/dashup#24]
While writing unit tests ive noticed that this method basically just sets the language so ill rename to updateLanguage.

**Comment by fidsusj** [comment]
But will it lateron not serve for changing themes, fonts, user credentials, etc. as well? Have a look at the change profile ucs

**Comment by joshuaschu** [comment]
i think we should differentiate i little bit when it comes to update cases, cause changing always all info would not be useful when just one single thing is changed but we can discuss that late on. For now ill rename and close this.
