### ISSUE TITLE
feature file "change_layout.feature"

### ISSUE THREAD

**Issue by joshuaschu** [raphaelmue/dashup#29]
some Questions and things that i would like to change cause of technical issues:
 *  Why do we need tons of examples for theme and font? This will cause builds that need hours to complete. I think it would be reasonable to change that to two or three just to assert that the code is working.

* How should we upload a picture to dashup while we are testing on jenkins? To insert a URL would be possible... like it is at settings at the moment

* line 19: How sould we test "clicks dashup icon OR navigates back over the nav bar"? Tests need to be clearly specified and should not contain "or". My proposal: delete one possibility or split this up in two tests

**Comment by fidsusj** [comment]
- You can restrict the number of tests for theme and font to two each

- If tests are not technically achievable then leave them away. This means a picture upload won't get tested

- split it up to two tests

Please remember to open a pull request before you merge. If things must be changed after review, please don't close the pull request but ask for confirmation again

**Comment by joshuaschu** [comment]
made changes on branch cucumber commit bb2874f. Closing.
