### ISSUE TITLE
Delete stale branchens

### ISSUE THREAD

**Issue by raphaelmue** [raphaelmue/dashup#64]
I'd like to delete the following branches:

- demo
- refactor
- webComponentsPolymer

Please check, whether there are commits that shall not be deleted. Else we can delete this branches to clean up our repository and to have less failing branches on jenkins.

**Comment by fidsusj** [comment]
Didn't you merge the refactor branch into your own refactoring branch when having refactored the repo?

**Comment by raphaelmue** [comment]
>Didn't you merge the refactor branch into your own refactoring branch when having refactored the repo?

Nope

**Comment by fidsusj** [comment]
I think you can even delete webComponentsCustom and panels as all components are developed in the components branch
